name: apptarata
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.9.0
  http: ^1.2.2
  geolocator: ^13.0.1
  flutter_polyline_points: ^2.1.0
  video_player: ^2.5.1
  carousel_slider: ^5.0.0
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/videos/